# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"

members = [
    "packages/*",
]

[workspace.package]
version = "0.1.0"
authors = ["Nic McPhee", "Many cool people on Twitch"]
description = "An evolutionary computation system in Rust"
documentation = "https://github.com/NicMcPhee/rust-ga"
edition = "2021"

[profile.release]
debug = true

[workspace.dependencies]
push_macros = { path = "packages/push-macros" }
