allowed-duplicate-crates = [
  "rand",
  "rand_chacha",
  "rand_core",
  "base64",
  "itertools",
  "syn",
  "heck",
  # https://github.com/eminence/terminal-size/pull/62
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc"
]
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
