allowed-duplicate-crates = [
  "rand",
  "rand_chacha",
  "rand_core",
  "base64",
  "itertools",
  "syn",
  "heck",
  # https://github.com/eminence/terminal-size/pull/62
  "windows-sys",
  # Updated dependencies of rand@0.9.x-beta.x, which the current ecosystem is currently behind of
  "zerocopy",
  "zerocopy-derive",
  "wasi",
  "getrandom"
]
