[package]
name = "ec_macros"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
categories = ["development-tools"]
# keywords = ["push", "proc-macros", "builder-pattern"]
readme = "README.md"

[lib]
proc-macro=true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manyhow = "0.11.4"
proc-macro2 = "1.0.81"
quote = "1.0.33"
syn = { version = "2.0.58", features = ["full", "printing"] }
