[package]
name = "rust-lexicase"
version = "0.1.0"
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
categories = ["algorithms"]
keywords = ["lexicase-selection", "genetic", "evolutionary-computation"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_lexicase"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.1", features = ["anyhow"] }
ec-core = { path = "../ec-core" }
numpy = "0.19.0"
rand = { workspace = true }

[lints]
workspace = true

